### PR TITLE
1.3.0 Release

### PR DESCRIPTION
**Pull request by guidoferreyra**
@JohnPhamous this pull request includes many changes with fixes and enhancements. With this changes merged we can release version 1.3.0. These are the corresponding binaries.

[GeistMono-1.2.0.zip](https://github.com/vercel/geist-font/files/14743627/GeistMono-1.2.0.zip)
[Geist-1.2.0.zip](https://github.com/vercel/geist-font/files/14743628/Geist-1.2.0.zip)

I have a draft for the release ready to be published after the merge, but let me know if you need to make changes on the npm package first.

### Noteworthy changes
- Improved drawing quality of base letters, numbers, diacritics.
- Heaviest master x-height raised for better optical compensation.
- Extended kerning to accented letters.
- Improved drawing quality of base glyphs
- Fixed vertical caron design
- Added missing box drawing character https://github.com/vercel/geist-font/issues/64
- Set Regular master as default instance https://github.com/vercel/geist-font/issues/68
- Fixed size of ordfemenine and ordmasculine
- Removed unnecesary full width punctuation
- Fixed width of small figures
- Improved set up for auto hinting
- Fixed Vertical metrics to avoid clipping on Windows
- Small drawing fixes in other glyphs

### CODE REVIEW

**Review by JohnPhamous — APPROVED** [review]

**Comment by JohnPhamous** [comment]
One sec, I'll update the package in this PR too

**Review by JohnPhamous — APPROVED** [review]

**Comment by guidoferreyra** [comment]
> One sec, I'll update the package in this PR too.
> 
> Gonna publish to 1.3.0 instead of 1.2.0 since the latter was used already.

So I guess, we should bump the version number on the fonts too.

**Comment by guidoferreyra** [comment]
Or maybe since the release has been already published we can do it on the next update. What do you think?

**Comment by JohnPhamous** [comment]
@guidoferreyra For the release yesterday

- I renamed the folder names in the Zips for the assets.

Where else do we need to update the version number?

**Comment by guidoferreyra** [comment]
The version number in the font binaries, is on the font table data.

**Pull request merged**
